vim.opt.grepprg = "rg --vimgrep --no-messages --smart-case"
vim.opt.splitright = true
vim.opt.splitbelow = false
vim.opt.inccommand = "split"
vim.opt.hlsearch = false
vim.opt.number = false
vim.opt.cursorline = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.undodir = os.getenv "HOME" .. "/.cache/nvim/undodir"
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "100"
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.updatetime = 50
vim.opt.completeopt = "menuone,noselect,fuzzy,noinsert"
vim.opt.termguicolors = true
vim.opt.smoothscroll = true
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus"
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.path:append { "**" }
vim.opt.wildoptions:append { "fuzzy" }
vim.wo.signcolumn = "yes"
vim.smartindent = true
