#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name            = "musaubrian"
email           = "musaubrian15@gmail.com"

[ui]
default-command = "log"
diff-editor     = ":builtin"

# [signing]
# behavior        = "own"
# backend         = "ssh"
# path            = "/home/smin/.ssh/signing.pub"

[aliases]
difft           = ["diff", "--tool=difft"]
