vim.opt.grepprg = "rg --vimgrep --no-messages --smart-case"
vim.opt.splitright = true
vim.opt.splitbelow = false
vim.opt.inccommand = "split"
vim.opt.hlsearch = false
vim.opt.number = false
vim.opt.cursorline = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.undodir = os.getenv "HOME" .. "/.cache/nvim/undodir"
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "100"
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.smartindent = true
vim.o.mouse = "a"
vim.o.clipboard = "unnamedplus"
vim.o.undofile = true
vim.o.ignorecase = false --Messed with the visual block find and replace
vim.o.smartcase = true
vim.wo.signcolumn = "yes"
vim.o.updatetime = 50
vim.o.completeopt = "menuone,noselect"
vim.o.termguicolors = true
